### PR TITLE
Replace a use of keySet() with entrySet()

### PR DESCRIPTION
**Pull request by kostis**
It's pointless to construct (and iterate over) the set of all keys of a Map data structure if the intention is to iterate over all the entries. This is what the entrySet allows and is there for.

### CODE REVIEW

**Review by actyp — APPROVED** [review]
Yes, it is better this way.

**Comment by kostis** [comment]
I've quickly checked the other 5 cases where `keySet()` appears, but could not see how to possibly transform them.
If you have some cycles to spare, perhaps you can come up with some imaginative way(s), and include them in this PR, or also confirm that they can not be tranformed.

**Comment by actyp** [comment]
Only one instance could be updated. The other ones are fine and cannot be transformed.

**Comment by kostis** [comment]
Thanks for looking into this.  I will merge.

**Pull request merged**
